site_name: Les maths à Mimard
site_author: Lycée Mimard

# Repository
use_directory_urls : false
# Copyright


# Configuration
#theme:
#  name: material
#  language: fr
#  palette:
#    primary: light green
#    accent: lime
#  font:
#    text: Ubuntu
#    code: Ubuntu Mono

# Extras


# Google Analytics

# Extensions
   
#theme: readthedocs
theme:
    name: 'material'
    language: 'fr'
    palette:
        primary: 'light green'
        accent: 'amber'
    features:
        tabs : false
        #- navigation.tabs
        #- navigation.tabs.sticky
        
        
        
extra_css: 
    - 'Style/extra.css'
    - 'Style/print.css'
    
extra_javascript:
  #- 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
    
#https://python-markdown.github.io/extensions/
#https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
#https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions

markdown_extensions:
    - tables
    - pymdownx.critic
    - attr_list #https://python-markdown.github.io/extensions/attr_list/
    - md_in_html
    - pymdownx.arithmatex: #https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
        generic: true
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: true
    - pymdownx.details #https://facelessuser.github.io/pymdown-extensions/extensions/details/
    - pymdownx.superfences #https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg 
          #https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
          #https://www.emojicopy.com/
    - meta  # https://squidfunk.github.io/mkdocs-material/extensions/metadata/
    - codehilite:  
        linenums: true  # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/ 
    - admonition  #https://squidfunk.github.io/mkdocs-material/extensions/admonition/
    - toc:
        permalink: '' #'🔗'
        baselevel: 1
        separator: "_"

nav:
    - Accueil: "index.md"
    - Cours: 
        - Accueil: "Cours/c01.md"
        - Seconde: "Cours/Seconde/c01.md"
        - Première NSI: 
            - Présentation: "Cours/Première NSI/Présentation/c01.md"
            - Les bases:
                - "Bien écrire en python": "Cours/Première NSI/Python/Les bases/ortho.md"
                - "Méthodes de base : print/input": "Cours/Première NSI/Python/Les bases/in_out.md"                
                - "Méthodes de base : chaine de caractères": "Cours/Première NSI/Python/Les bases/str.md"
        - Première STI2D: "Cours/Première STI2D/c01.md"
        - Terminale STI2D: "Cours/Terminale STI2D/c01.md"
        - Première générale: "Cours/Première générale/c01.md"
        - Terminale générale:
            - Accueil TGEN: "Cours/Terminale générale/index_term_G.md"
            - Dérivation, convexité et primitive:
                - "Dérivation : les bases":
                    - Dérivation et tangente: "Cours/Terminale générale/Derivation_et_convexite/Dérivation - les bases/01_deriv_base_tgte.md"
                    - Dérivation et formule: "Cours/Terminale générale/Derivation_et_convexite/Dérivation - les bases/02_deriv_base_formule.md"
                    - Utilisation de la dérivée: "Cours/Terminale générale/Derivation_et_convexite/Dérivation - les bases/03_deriv_utilis.md"
                    - Composée de fonctions: "Cours/Terminale générale/Derivation_et_convexite/Dérivation - les bases/04_deriv_composee.md"
            - "Suite et récurrence":
                - Rappel sur les suites: "Cours/Terminale générale/Suites_et_recurrence/01_Rappels_sur_les_suites.md"
                - Suites et python: "Cours/Terminale générale/Suites_et_recurrence/02_Suites_et_python.md"
                - Suites et sens de variations: "Cours/Terminale générale/Suites_et_recurrence/03_Suite_et_sens_de_variations.md"
                - Suites arithmétiques: "Cours/Terminale générale/Suites_et_recurrence/04_Suites_aritmetiques.md"
                - Suites géométriques: "Cours/Terminale générale/Suites_et_recurrence/05_Suites_geometrique.md"
                - Raisonnement par récurrence: "Cours/Terminale générale/Suites_et_recurrence/06_Raisonnement_par_recurrence.md"
                - Suite majorée, minorée, bornée: "Cours/Terminale générale/Suites_et_recurrence/07_majoree_minoree_bornee.md"
            - Limite de suite:
                - Limite d'une suite: "Cours/Terminale générale/Limite_de_suite/01_Limite_d_une_suite.md"
                - Limite de la suite $q^n$: "Cours/Terminale générale/Limite_de_suite/02_Limite_de_la_suite_qn.md"
                - Limite et opérations: "Cours/Terminale générale/Limite_de_suite/03_Theoremes_d_operation.md"
    - Labo de math: 
        - Accueil: "Labo de math/c01.md"
        - "Liaison lycée/supérieur": "/Labo de math/Liaison_lycée_sup/supérieur.md"
