site_name: Maths et NSI
site_author: Lycée
site_url: https://boulotacademique.github.io/site_lycee_essai/

repo_url: https://github.com/boulotacademique/site_lycee_essai
#edit_uri: projetEssai/docs

docs_dir : docs

# Repository
#use_directory_urls : false
# Copyright


# Configuration
#theme:
#  name: material
#  language: fr
#  palette:
#    primary: light green
#    accent: lime
#  font:
#    text: Ubuntu
#    code: Ubuntu Mono

# Extras


# Google Analytics

# Extensions
   
#theme: readthedocs
theme:
    name: 'material'
    language: 'fr'
    custom_dir: docs/my_theme_customizations/
    features:
        - instant
        - tabs
        - top
        - toc.integrate
        - header.autohide
        #- navigation.tabs.
    # palette:
    #     primary: 'light green'
    #     accent: 'amber'
    palette:
      - scheme: default
        toggle:
          icon: material/weather-sunny
          name: Basculer en mode sombre
      - scheme: slate
        #primary: 'light green'
        #accent: amber
        toggle:
          icon: material/weather-night
          name: Basculer en mode clair


    features:
        - navigation.instant
        - navigation.tabs
        - navigation.top
        # - toc.integrate
        - header.autohide
        #- navigation.tabs.sticky
    

extra_css: 
    - 'Style/extra.css'
    - 'Style/print.css'
    #- 'dist/reveal.css'
    #- 'dist/theme/black.css'


# reveal:
#   path: dist
#   transition: slide
#   theme:
#     name: source/white.css
#     path: css/theme
#   plugin:
#     path: plugin


extra_javascript:
  #- 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    #- E:/Travail/MathJax/MathJax-2.7.3/mathjax.js
    - javascripts/mathjax.js
    - javascripts/my_java.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    #- javascripts/reveal/reveal.js-master/js/reveal.js

    
    
#https://python-markdown.github.io/extensions/
#https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
#https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions

markdown_extensions:
    - abbr
    - def_list
    - footnotes
    - tables
    - pymdownx.critic
    - pymdownx.keys
    - attr_list #https://python-markdown.github.io/extensions/attr_list/
    - md_in_html
    - pymdownx.arithmatex: #https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
        generic: true
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: true
    - pymdownx.details #https://facelessuser.github.io/pymdown-extensions/extensions/details/
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.highlight
    - pymdownx.inlinehilite
    # - pymdownx.snippets
    - pymdownx.superfences #https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
    # - pymdownx.tabbed:
    #     alternate_style: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:pymdownx.emoji.to_svg 
          #https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
          #https://www.emojicopy.com/
    - meta  # https://squidfunk.github.io/mkdocs-material/extensions/metadata/
    - codehilite:  
        linenums: true  # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/ 
    - admonition  #https://squidfunk.github.io/mkdocs-material/extensions/admonition/
    - toc:
        permalink: '' #'🔗'
        baselevel: 1
        separator: "_"

plugins:
    - search
    - macros
    - exclude:
        glob:
            - "*.py"
#     - mkdocs-jupyter:
#         include_source: true

nav:
    - "":
        - "Cours/c01.md"
        - "Cours/Première NSI/c01.md"
        - "Cours/Première NSI/Accueil/c01.md"
        - "Cours/Première NSI/Codage/Au programme/Le son/c01.md"
        - "Cours/Première NSI/Codage/Au programme/Les images/c01.md"
        - "Cours/Première STI2D/c01.md"
        - "Cours/Première générale/c01.md"
        - "Cours/Seconde/c01.md"
        - "Cours/Terminale STI2D/c01.md"
        - "Cours/Terminale générale/Derivation_et_convexite/01_Fonction_derivable.md"
        - "Cours/Terminale générale/Esp_ortho/Esp_ortho_prog/ortho_esp_dem.md"
        - "my_theme_customizations/pyodide-mkdocs/end_REM.md" 
        - "my_theme_customizations/pyodide-mkdocs/start_REM.md" 
    - Accueil: "index.md"
    #- Seconde: "Cours/Seconde/c01.md"
    - Première NSI: 
        - Présentation: "Cours/Première NSI/Présentation/c01.md"
        - Python:
            - Les bases:  
                - "Bien écrire en python": "Cours/Première NSI/Python/Les bases/ortho.md"
                - "Variables, opérations" : "Cours/Première NSI/Python/Les bases/variables.md"
                - "print/input": "Cours/Première NSI/Python/Les bases/in_out.md"                
                - "Chaine de caractères": "Cours/Première NSI/Python/Les bases/str.md"
                - "La boucle for" : "Cours/Première NSI/Python/Les bases/for.md"
                - "if, elif et les conditions" : "Cours/Première NSI/Python/Les bases/if_elif.md"
                - "La boucle while" : "Cours/Première NSI/Python/Les bases/while.md"
                - "Les listes (I)" : "Cours/Première NSI/Python/Les bases/list.md"
                - "Les fonctions" : "Cours/Première NSI/Python/Les bases/fct.md"
            - Les structures:
                - "Les listes (II)" : "Cours/Première NSI/Python/Structures/list02.md"
                - "Les matrices" : "Cours/Première NSI/Python/Structures/matrice.md"
                - "Les dictionnaires" : "Cours/Première NSI/Python/Structures/dico.md"
        - Codage :
            - Les bases :
                - "Codage d'entier positif": "Cours/Première NSI/Codage/Les bases/Binaire/01_codage_entier.md"
                - "Codage d'entier négatif": "Cours/Première NSI/Codage/Les bases/Binaire/02_codage_negatif.md"
                - "Codage en hexadécimal": "Cours/Première NSI/Codage/Les bases/Hexadécimal/03_hexadécimal.md"
                - "Codage des caractères : ASCII" : "Cours/Première NSI/Codage/Les bases/Les_caracteres/04_caract_ASCII.md"
                - "Codage des caractères et python" : "Cours/Première NSI/Codage/Les bases/Les_caracteres/05_iso-8859-1.md"
                - "Codage des réels" : "Cours/Première NSI/Codage/Les bases/Les flottants/01_manip_reel.md"
            - Au programme:
                - "Codage des caractères : ISO-8859-15" : "Cours/Première NSI/Codage/Au programme/Les_caracteres_suite/06_iso-8859-15.md"
                - "Codage des caractères : UTF-8" : "Cours/Première NSI/Codage/Au programme/Les_caracteres_suite/07_UTF8.md" 
                - "Codage des réels (suite)" :  "Cours/Première NSI/Codage/Au programme/Les flottants_suite/02_flottant.md"

## ISO-8859-15 (Facultatif)
    #- Première STI2D: "Cours/Première STI2D/c01.md"
    #- Terminale STI2D: "Cours/Terminale STI2D/c01.md"
    #- Première générale: "Cours/Première générale/c01.md"
    - Terminale générale:
        - Accueil TGEN: "Cours/Terminale générale/index_term_G.md"
        - Dérivation, convexité, primitive:
            - "Dérivation : les bases":
                - Dérivation et tangente: "Cours/Terminale générale/Derivation_et_convexite/Dérivation - les bases/01_deriv_base_tgte.md"
                - Dérivation et formule: "Cours/Terminale générale/Derivation_et_convexite/Dérivation - les bases/02_deriv_base_formule.md"
                - Utilisation de la dérivée: "Cours/Terminale générale/Derivation_et_convexite/Dérivation - les bases/03_deriv_utilis.md"
                - Composée de fonctions: "Cours/Terminale générale/Derivation_et_convexite/Dérivation - les bases/04_deriv_composee.md"
                - Convexité: "Cours/Terminale générale/Derivation_et_convexite/Dérivation - les bases/05_Convexite.md"
            - "Dérivation : au programme":
                - "A retenir": "Cours/Terminale générale/Derivation_et_convexite/Dérivation_au_prog/Deriv_A_retenir.md"
                - Nombre dérivé: "Cours/Terminale générale/Derivation_et_convexite/Dérivation_au_prog/Nbre_dérivé.md"
                - Convexité et inégalités: "Cours/Terminale générale/Derivation_et_convexite/Dérivation_au_prog/conv_ineg.md"
                - Démonstration au programme: "Cours/Terminale générale/Derivation_et_convexite/Dérivation_au_prog/dem_prog.md"
            - "Dérivation : vers le supérieur": "Cours/Terminale générale/Derivation_et_convexite/Dérivation_en_plus/Dérivation_best.md"
        - "Suite et récurrence":
            - "Suites : les bases":
                - Rappel sur les suites: "Cours/Terminale générale/Suites_et_recurrence/Suites_bases/01_Rappels_sur_les_suites.md"
                - Suites et python: "Cours/Terminale générale/Suites_et_recurrence/Suites_bases/02_Suites_et_python.md"
                - Suites et sens de variations: "Cours/Terminale générale/Suites_et_recurrence/Suites_bases/03_Suite_et_sens_de_variations.md"
                - Suites arithmétiques: "Cours/Terminale générale/Suites_et_recurrence/Suites_bases/04_Suites_aritmetiques.md"
                - Suites géométriques: "Cours/Terminale générale/Suites_et_recurrence/Suites_bases/05_Suites_geometrique.md"
                - Raisonnement par récurrence: "Cours/Terminale générale/Suites_et_recurrence/Suites_bases/06_Raisonnement_par_recurrence.md"
                - Suite majorée, minorée, bornée: "Cours/Terminale générale/Suites_et_recurrence/Suites_bases/07_majoree_minoree_bornee.md"
            - "Suites : au programme":
                - "A retenir": "Cours/Terminale générale/Suites_et_recurrence/Suites_prog/SuiteRec_A_retenir.md"
        - Loi binomiale:
            - "Probabilité : les bases":
                - Rappel: "Cours/Terminale générale/Loi_binomiale/binom_bases/01_binom_rappel.md"
                - Succession d'épreuves: "Cours/Terminale générale/Loi_binomiale/binom_bases/02_succ_ep_ind.md"
                - Loi binomiale: "Cours/Terminale générale/Loi_binomiale/binom_bases/03_loi_binom.md"
            - "Probabilités : au programme": 
                - A retenir: "Cours/Terminale générale/Loi_binomiale/binom_prog/binom_A_Retenir.md"
                - Démonstration au programme: "Cours/Terminale générale/Loi_binomiale/binom_prog/binom_dem_prog.md"
        - Limite de suite:
            - "Limite de suites : les bases":
                - Limite d'une suite: "Cours/Terminale générale/Limite_de_suite/Limite_suite_base/01_Limite_d_une_suite.md"
                - Limite de la suite $q^n$: "Cours/Terminale générale/Limite_de_suite/Limite_suite_base/02_Limite_de_la_suite_qn.md"
                - Limite et opérations: "Cours/Terminale générale/Limite_de_suite/Limite_suite_base/03_Theoremes_d_operation.md"
                - Limite et comparaison : "Cours/Terminale générale/Limite_de_suite/Limite_suite_base/04_th_comp.md"
            - "Limite de suites : au programme": 
                - A retenir: "Cours/Terminale générale/Limite_de_suite/lim_suite_prog/lim_suite_A_retenir.md"
                - "Démonstrations au programme": "Cours/Terminale générale/Limite_de_suite/lim_suite_prog/lim_suite_dem_prog.md"
            - "Limite de suites : vers le supérieur": "Cours/Terminale générale/Limite_de_suite/Limite_de_suite_en_plus/limite_suite_best.md"
        - Vecteur de l'espace:
            - "Vecteur : les bases":
                - Perspective cavalière: "Cours/Terminale générale/Vecteur_esp/vect_esp_base/persp_cav.md"
                - Droite et plan: "Cours/Terminale générale/Vecteur_esp/vect_esp_base/dte_et_plan.md"
                - Vecteur de l'espace: "Cours/Terminale générale/Vecteur_esp/vect_esp_base/Vect_esp.md"
                - Repère de l'espace: "Cours/Terminale générale/Vecteur_esp/vect_esp_base/rep_esp.md"
                - Equation paramétrique d'une droite: "Cours/Terminale générale/Vecteur_esp/vect_esp_base/Eq_param.md"
            - "Vecteur : au programme":
                - "A retenir" : "Cours/Terminale générale/Vecteur_esp/vect_esp_prog/vect_esp_A_Retenir.md"
        - Limite de fonction:
            - "Limite de fct : les bases":
                - "Limite vers l'infini": "Cours/Terminale générale/Limite_fct/limite_fct_base/01_lim_fct_infinie.md"
                - "Limite au voisinage d'un réel": "Cours/Terminale générale/Limite_fct/limite_fct_base/02_lim_fct_reel.md"
                - "Limite et opérations": "Cours/Terminale générale/Limite_fct/limite_fct_base/03_lim_fct_op.md"
                - "Limite et comparaison": "Cours/Terminale générale/Limite_fct/limite_fct_base/04_lim_fct_comp.md"
            - "Limite de fct : au programme": 
                - A retenir: "Cours/Terminale générale/Limite_fct/limite_fct_prog/lim_fct_A_Retenir.md"
                - "Démonstration au programme" : "Cours/Terminale générale/Limite_fct/limite_fct_prog/lim_fct_dem.md" 
        - Orthogonalité dans l'espace:
            - "Orthogonalité : les bases":
                - "Rappel : produit scalaire dans le plan": "Cours/Terminale générale/Esp_ortho/Esp_ortho_base/01_Rappel_pdt_scal_plan.md"
                - "Espace et produit scalaire": "Cours/Terminale générale/Esp_ortho/Esp_ortho_base/02_pdt_scal_esp.md"
                - "Vecteur normal": "Cours/Terminale générale/Esp_ortho/Esp_ortho_base/03_vect_normal.md"
                - "Equation cartésienne, distance": "Cours/Terminale générale/Esp_ortho/Esp_ortho_base/04_eq_cart_plan.md"
            - "Orthogonalité : au programme":
                - A retenir: "Cours/Terminale générale/Esp_ortho/Esp_ortho_prog/Esp_ortho_A_Retenir.md"
                - "Plan médiateur": "Cours/Terminale générale/Esp_ortho/Esp_ortho_prog/Plan_med.md"
        - Continuité:
            - "Continuité : les bases":
                - Fonction continue: "Cours/Terminale générale/Continuite/Continuite_base/01_cont_fct.md"
                - Théorème des valeurs intermédiaires: "Cours/Terminale générale/Continuite/Continuite_base/02_TVI.md"
            - "Continuité : au programme":
                - A retenir: "Cours/Terminale générale/Continuite/Continuite_prog/Continuite_A_Retenir.md"
        - Logarithme népérien:
            - "Log népérien : les bases": 
                - "La fonction ln": "Cours/Terminale générale/Log/Log_base/01_fct_ln.md"
                - "Etude de la fonction": "Cours/Terminale générale/Log/Log_base/02_etude_fct.md"
            - "Log népérien : au programme" : 
                - A retenir: "Cours/Terminale générale/Log/Log_prog/Log_A_Retenir.md"
        - Equation différentielle:
            - "Eq diff : les bases":
                - "Définition" : "Cours/Terminale générale/Eq_diff/Eq_diff_base/01_Def.md"
                - Eq. diff. premier ordre: "Cours/Terminale générale/Eq_diff/Eq_diff_base/02_ED1.md"
            - "Eq diff : au programme":
                - "Démonstration au programme": "Cours/Terminale générale/Eq_diff/Eq_diff_prog/Dem_prog.md"
        - Ensemble:
            - "Ensemble : les bases": 
                - Ensemble: "Cours/Terminale générale/Ensemble/Ensemble_base/01_ensemble.md"
                - Dénombrement: "Cours/Terminale générale/Ensemble/Ensemble_base/02_denom.md"
            - "Ensemble : Au programme":
                - "Démonstration au programme": "Cours/Terminale générale/Ensemble/Ensemble_prog/Dem_prog.md"
        - Calcul intégral:
            - "Intégrale : les bases":
                - "Fonctions positives" : "Cours/Terminale générale/Calcul_integral/Cal_int_base/01_fct_pos.md"
                - "Fonctions positives et primitives": "Cours/Terminale générale/Calcul_integral/Cal_int_base/02_fct_pos_prim.md"
                - "Fonctions quelconques" : "Cours/Terminale générale/Calcul_integral/Cal_int_base/03_fct_qcq.md"
                - "Intégration par parties": "Cours/Terminale générale/Calcul_integral/Cal_int_base/04_int_pp.md"
                - "Calcul d'aire": "Cours/Terminale générale/Calcul_integral/Cal_int_base/05_calc_aire.md" 
            - "Intégrale : au programme":
                - "Démonstration au programme" : "Cours/Terminale générale/Calcul_integral/Cal_int_prog/Dem_prog.md"
        - Somme de variable aléatoire:
            - "Variable aléatoire : les bases":
                - "Tout le cours": "Cours/Terminale générale/Somme_VAR/VAR_base/01_var.md"
        - Fonction trigonomértique:
            - "Fct trigo : les bases":
                - "Tout le cours": "Cours/Terminale générale/Fct_trigo/Fct_trigo_base/01_trigo.md"
        - Loi des grands nombres:
            - "Lois des grands nombres : les bases":
                - "Tout le cours": "Cours/Terminale générale/Loi_gds_nombres/Gds_nbres_bases/01_gds_nbres.md"
    - Labo de math:  
        - Accueil: "Labo de math/c01.md"
        - "Liaison lycée/supérieur": "Labo de math/Liaison_lycée_sup/supérieur.md"
        #- "essai slide" : "Labo de math/Liaison_lycée_sup/essai_slide.md"
