site_name: Spé Math
site_author: Lycée Mimard

# Repository
use_directory_urls : false
# Copyright


# Configuration
theme:
  name: material
  language: fr
  palette:
    primary: light green
    accent: lime
  font:
    text: Ubuntu
    code: Ubuntu Mono

# Extras


# Google Analytics

# Extensions
   
#theme: readthedocs
theme:
    name: 'material'
    language: 'fr'
    palette:
        primary: 'light green'
        accent: 'amber'
    feature:
        tabs: false
        
        
        
extra_css: 
    - 'Style/extra.css'
    - 'Style/print.css'
    
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    
    
#https://python-markdown.github.io/extensions/
#https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
#https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions

markdown_extensions:
    - attr_list #https://python-markdown.github.io/extensions/attr_list/
    - pymdownx.arithmatex #https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: true
    - pymdownx.details #https://facelessuser.github.io/pymdown-extensions/extensions/details/
    - pymdownx.superfences #https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg 
          #https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
          #https://www.emojicopy.com/
    - meta  # https://squidfunk.github.io/mkdocs-material/extensions/metadata/
    - codehilite:  
        linenums: true  # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/ 
    - admonition  #https://squidfunk.github.io/mkdocs-material/extensions/admonition/
    - toc:
        permalink: '' #'🔗'
        baselevel: 1
        separator: "_"
